#![allow(non_camel_case_types)]
//! This file was automatically generated using the following command:
//!
//! ```bash
//! tools/gen-rust-rpc.py doc/schemas/getinfo.request.json cln-rpc/src/requests/getinfo.rs
//! ```
//!
//! Do not edit this file, it'll be overwritten. Rather edit the schema that
//! this file was generated from

#[allow(unused_imports)]
use crate::primitives::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Getinfo {
}

