#ifndef LIGHTNING_LIGHTNINGD_PLUGIN_REQUEST_H
#define LIGHTNING_LIGHTNINGD_PLUGIN_REQUEST_H

#include "config.h"
#include <ccan/autodata/autodata.h>
#include <ccan/tal/tal.h>
#include <ccan/typesafe_cb/typesafe_cb.h>
#include <lightningd/json_stream.h>
#include <lightningd/lightningd.h>
#include <lightningd/plugin.h>

enum request_async_prio {
	LIGHTNINGD_PLUGIN_REQUEST_LOW_PRIO,
	LIGHTNINGD_PLUGIN_REQUEST_HIGH_PRIO
};
#define LIGHTNINGD_PLUGIN_REQUEST_NUM_PRIO (LIGHTNINGD_PLUGIN_REQUEST_HIGH_PRIO+1)

struct plugin_request_manager {
	/* Main plugins manager */
	struct plugins *plugins;

	/* How many high/low prio requests are we running (it's ratelimited) */
	size_t num_requests[LIGHTNINGD_PLUGIN_REQUEST_NUM_PRIO];

	/* Pending requests (high and low prio). */
	struct list_head pending[LIGHTNINGD_PLUGIN_REQUEST_NUM_PRIO];

	/* If non-zero, time the plugin hits a error. */
	unsigned int error_count;
	struct timemono first_error_time;

	/* Ignore results, we're shutting down. */
	bool shutdown;

	/* FIXME: make it an option like retry_timeout for bitcoind */
	/* How long to keep trying to contact bitcoind
	 * before fatally exiting. */
	u64 retry_timeout;
};

struct plugin_request_manager *new_plugin_request_manager(const tal_t *ctx,
			      struct plugins *plugins);

struct plugin_request {
	const char *name;
	bool (*response_cb)(void *arg, const char *buffer,
			    const jsmntok_t *errortoks);
	void (*serialize_payload)(void *src, struct json_stream *dest);

	/* Which plugin has registered this request? */
	struct plugin *plugin;
};
AUTODATA_TYPE(requests, struct plugin_request);

/* Do not call this directly, rather use the `plugin_request_call_name`
 * wrappers generated by the `PLUGIN_REQUEST_REGISTER` macro.
 */
void plugin_request_call_(struct lightningd *ld,
		          const struct plugin_request *request, void *payload,
		          void *cb_arg, enum request_async_prio prio,
		          u64 *reply_timeout);

/* Create a small facade in from of `plugin_request_call_` to make sure
 * arguments are of the correct type before downcasting them to `void
 * *`. Not really necessary, but nice since it also makes sure that
 * the method-name is correct for the call.
 */
/* FIXME: Find a way to avoid back-to-back declaration and definition */
#define PLUGIN_REQUEST_CALL_DEF(name, payload_type, response_cb_arg_type)         \
	UNNEEDED static inline void plugin_request_call_##name(                   \
	    struct lightningd *ld,                                             \
	    payload_type payload,                                              \
	    response_cb_arg_type cb_arg,                                       \
	    enum request_async_prio prio,                                      \
	    u64 *reply_timeout)                                                \
	{                                                                      \
		plugin_request_call_(ld, &name##_request_gen, (void *)payload,       \
				     (void *)cb_arg, prio, reply_timeout);                             \
	}

/* Typechecked registration of a plugin request. We check that the
 * serialize_payload function converts an object of type payload_type
 * to a json_stream (.params object in the JSON-RPC request), that the
 * deserialize_response function converts from the JSON-RPC response
 * json_stream to an object of type response_type and that the
 * response_cb function accepts the deserialized response format and
 * an arbitrary extra argument used to maintain context.
 */
#define REGISTER_PLUGIN_REQUEST(name, response_cb, response_cb_arg_type,          \
			     serialize_payload, payload_type)                  \
	struct plugin_request name##_request_gen = {                                 \
	    stringify(name),                                                   \
	    typesafe_cb_cast(bool (*)(void *, const char *,                    \
				      const jsmntok_t *),                      \
			     bool (*)(response_cb_arg_type, const char *,      \
				      const jsmntok_t *),                      \
			     response_cb),                                     \
	    typesafe_cb_cast(void (*)(void *, struct json_stream *),           \
			     void (*)(payload_type, struct json_stream *),     \
			     serialize_payload),                               \
	    NULL, /* .plugin */                                                \
	};                                                                     \
	AUTODATA(requests, &name##_request_gen);                                     \
	PLUGIN_REQUEST_CALL_DEF(name, payload_type, response_cb_arg_type);

bool plugin_request_register(struct plugin *plugin, const char *method);

#endif /* LIGHTNING_LIGHTNINGD_PLUGIN_REQUEST_H */
