import json

from pyln.client.lightning import RpcError

from fixtures import *  # noqa: F401,F403
import subprocess
from pathlib import Path
from pyln.testing.utils import VALGRIND
import os
import re
import time
import unittest
import pytest


@pytest.fixture(autouse=True)
def canned_github_server(directory):
    global NETWORK
    NETWORK = os.environ.get("TEST_NETWORK")
    if NETWORK is None:
        NETWORK = "regtest"
    FILE_PATH = Path(os.path.dirname(os.path.realpath(__file__)))
    if os.environ.get("LIGHTNING_CLI") is None:
        os.environ["LIGHTNING_CLI"] = str(FILE_PATH.parent / "cli/lightning-cli")
        print("LIGHTNING_CALL: ", os.environ.get("LIGHTNING_CLI"))
    global my_env
    my_env = os.environ.copy()
    # This tells reckless to redirect to the canned server rather than github.
    os.environ["REDIR_GITHUB"] = os.path.join(directory, "lightningd")

    # Generate test plugin repository to test reckless against.
    repo_dir = os.path.join(directory, "lightningd")
    os.mkdir(repo_dir, 0o777)
    plugins_path = str(FILE_PATH / "data/recklessrepo/lightningd")

    # Create requirements.txt file for the testpluginpass
    # with pyln-client installed from the local source
    requirements_file_path = os.path.join(
        plugins_path, "testplugpass", "requirements.txt"
    )
    with open(requirements_file_path, "w") as f:
        pyln_client_path = os.path.abspath(
            os.path.join(FILE_PATH, "..", "contrib", "pyln-client")
        )
        f.write(f"pyln-client @ file://{pyln_client_path}\n")

    # This lets us temporarily set .gitconfig user info in order to commit
    my_env["HOME"] = directory
    with open(os.path.join(directory, ".gitconfig"), "w") as conf:
        conf.write(
            (
                "[user]\n"
                "\temail = reckless@example.com\n"
                "\tname = reckless CI\n"
                "\t[init]\n"
                "\tdefaultBranch = master"
            )
        )

    with open(os.path.join(directory, ".gitconfig"), "r") as conf:
        print(conf.readlines())

    # Bare repository must be initialized prior to setting other git env vars
    subprocess.check_output(["git", "init"], cwd=repo_dir, env=my_env)

    # my_env["GIT_DIR"] = os.path.join(repo_dir, "plugins")
    # my_env["GIT_WORK_TREE"] = repo_dir
    # my_env["GIT_INDEX_FILE"] = os.path.join(repo_dir, "scratch-index")
    repo_initialization = (
        f"cp -r {plugins_path}/* .;"
        "git add --all;"
        'git commit -m "initial commit - autogenerated by test_reckless.py";'
        "git remote add origin ./;"
        "git fetch origin;"
        "git checkout -B master origin/master;"
    )
    tag_and_update = (
        "git tag v1;"
        "sed -i.bak 's/v1/v2/g' testplugpass/testplugpass.py;"
        "rm -f testplugpass/testplugpass.py.bak;"
        "git add testplugpass/testplugpass.py;"
        'git commit -m "update to v2";'
        "git tag v2;"
    )
    subprocess.check_output([repo_initialization], env=my_env, shell=True, cwd=repo_dir)
    subprocess.check_output([tag_and_update], env=my_env, shell=True, cwd=repo_dir)
    del my_env["HOME"]
    # del my_env["GIT_DIR"]
    # del my_env["GIT_WORK_TREE"]
    # del my_env["GIT_INDEX_FILE"]
    yield
    # Delete requirements.txt from the testplugpass directory
    with open(requirements_file_path, "w") as f:
        f.write("pyln-client\n\n")


class RecklessResult:
    def __init__(self, process, returncode, stdout, stderr):
        self.process = process
        self.returncode = returncode
        self.stdout = stdout
        self.stderr = stderr

    def __repr__(self):
        return "self.returncode, self.stdout, self.stderr"

    def search_stdout(self, regex):
        """return the matching regex line from reckless output."""
        ex = re.compile(regex)
        matching = []
        for line in self.stdout:
            if ex.search(line):
                matching.append(line)
        return matching


def check_stderr(logs):
    def output_okay(out):
        for warning in [
            "[notice]",
            "WARNING:",
            "npm WARN",
            "npm notice",
            "DEPRECATION:",
            "Creating virtualenv",
            "config file not found:",
            "press [Y]",
        ]:
            if out.startswith(warning):
                return True
        return False

    for e in logs:
        if len(e) < 1:
            continue
        # Don't err on verbosity from pip, npm
        if not output_okay(e):
            raise Exception(f"reckless stderr contains `{e}`")


SUBCOMMANDS = [
    "install",
    "uninstall",
    "listavailable",
    "enable",
    "disable",
    "source",
    "update",
    "listinstalled",
]


def test_help(node_factory):
    """Validate that reckless provides overall and subcommand help."""
    node = node_factory.get_node(options={})

    r = node.rpc.call("reckless", ["help"], filter={"format-hint": True})
    assert "Usage: reckless [OPTIONS] [COMMAND]" in r["result"]
    for subcommand in SUBCOMMANDS:
        assert subcommand in r["result"]

    r = node.rpc.call("reckless", [], filter={"format-hint": True})
    assert "Usage: reckless [OPTIONS] [COMMAND]" in r["result"]
    for subcommand in SUBCOMMANDS:
        assert subcommand in r["result"]

    for subcmd in SUBCOMMANDS:
        r = node.rpc.call("reckless", ["help", subcmd], filter={"format-hint": True})
        assert f"Usage: {subcmd}" in r["result"]


def test_sources(node_factory):
    """add additional sources and search through them"""
    n = node_factory.get_node(options={})
    r = n.rpc.call("reckless", ["source", "list", "-v"])
    print(r)
    assert "https://github.com/lightningd/plugins" in r["result"][0]["sources"]
    print(n.lightning_dir)
    reckless_dir = Path(n.lightning_dir) / "reckless"
    print(dir(reckless_dir))
    assert (reckless_dir / ".sources").exists()
    print(os.listdir(reckless_dir))
    print(reckless_dir / ".sources")
    plugin_dir = str(os.path.join(n.lightning_dir, "..", "lightningd"))
    r = n.rpc.call("reckless", ["source", "-v", "add", f"{plugin_dir}/testplugfail"])
    r = n.rpc.call("reckless", ["source", "-v", "add", f"{plugin_dir}/testplugpass"])
    with open(reckless_dir / ".sources") as sources:
        contents = [c.strip() for c in sources.readlines()]
        print("contents:", contents)
        assert "https://github.com/lightningd/plugins" in contents
        assert f"{plugin_dir}/testplugfail" in contents
        assert f"{plugin_dir}/testplugpass" in contents
    r = n.rpc.call(
        "reckless",
        [
            "source",
            "-v",
            "remove",
            f"{plugin_dir}/testplugfail",
        ],
    )
    print(r)
    with open(reckless_dir / ".sources") as sources:
        contents = [c.strip() for c in sources.readlines()]
        print("contents:", contents)
        assert f"{plugin_dir}/testplugfail" not in contents
        assert f"{plugin_dir}/testplugpass" in contents


def test_list_partial_match(node_factory):
    """test that partial/substring listavailable returns matches"""
    n = node_factory.get_node(options={})

    # Search for partial name "testplug" - should find all test plugins
    r = n.rpc.call("reckless", ["listavailable", "-v", "testplug"])
    # Should show the "Plugins matching" header
    assert "INFO: Plugins matching 'testplug':" in r["log"]
    # Should list multiple plugins (all start with "testplug")
    assert any("testplugpass" in line for line in r["log"])
    assert any("testplugfail" in line for line in r["log"])
    assert any("testplugpyproj" in line for line in r["log"])
    assert any("testpluguv" in line for line in r["log"])

    # Search for "pass" - should find testplugpass
    r = n.rpc.call("reckless", ["listavailable", "-v", "pass"])
    assert "INFO: Plugins matching 'pass':" in r["log"]
    assert any("testplugpass" in line for line in r["log"])
    # Should not find plugins without "pass" in name
    assert all("testplugfail" not in line for line in r["log"])

    # Search for something that doesn't exist
    r = n.rpc.call("reckless", ["listavailable", "-v", "nonexistent"])
    assert "INFO: Search exhausted all sources" in r["log"]


@unittest.skipIf(VALGRIND, "virtual environment triggers memleak detection")
def test_install(node_factory):
    """test search, git clone, and installation to folder."""
    n = node_factory.get_node(options={})
    r = n.rpc.call("reckless", ["install", "-v", "testplugpass"])
    assert r["result"][0]["enabled"]
    assert r["result"][0]["plugin_name"] == "testplugpass"
    assert any("dependencies installed successfully" in line for line in r["log"])
    assert any("plugin installed:" in line for line in r["log"])
    assert any("testplugpass enabled" in line for line in r["log"])
    # check_stderr(r["log"]) TODO: check logs
    plugin_path = Path(n.lightning_dir) / "reckless/testplugpass"
    print(plugin_path)
    assert os.path.exists(plugin_path)

    # Try to install again - should result in an error.
    with pytest.raises(RpcError, match="already installed"):
        n.rpc.call("reckless", ["install", "-v", "testplugpass"])
    n.daemon.wait_for_log("testplugpass is already installed")


@unittest.skipIf(VALGRIND, "virtual environment triggers memleak detection")
def test_install_cleanup(node_factory):
    """test failed start which should give a chance to enable with options and"""
    """a failed installation which should cleanup the plugin folder"""
    n = node_factory.get_node(
        options={},
        broken_log=".*uv failed.*|.*sofijowesifjwoiefjow.*|.*unsatisfiable.*|.*could not read metadata for testpluginvaliddeps.*",
    )
    r = n.rpc.call("reckless", ["install", "-v", "testplugreqopts"])
    assert not r["result"][0]["enabled"]
    assert r["result"][0]["plugin_name"] == "testplugreqopts"
    assert any("testplugreqopts failed to start" in line for line in r["log"])

    plugin_path = Path(n.lightning_dir) / "reckless/testplugreqopts"
    assert os.path.exists(plugin_path)

    with pytest.raises(RpcError, match="command .* failed"):
        n.rpc.call("reckless", ["install", "-v", "testpluginvaliddeps"])

    plugin_path = Path(n.lightning_dir) / "reckless/testpluginvaliddeps"
    assert not os.path.exists(plugin_path)


@unittest.skipIf(VALGRIND, "virtual environment triggers memleak detection")
def test_poetry_install(node_factory):
    """test search, git clone, and installation to folder."""
    n = node_factory.get_node(options={})
    r = n.rpc.call("reckless", ["install", "-v", "testplugpyproj"])
    assert any("dependencies installed successfully" in line for line in r["log"])
    assert any("plugin installed:" in line for line in r["log"])
    # time.sleep(120)
    assert any("testplugpyproj enabled" in line for line in r["log"])
    # check_stderr(r["log"]) TODO: check logs
    plugin_path = Path(n.lightning_dir) / "reckless/testplugpyproj"
    print(plugin_path)
    assert os.path.exists(plugin_path)
    print(n.rpc.testmethod())
    assert n.daemon.is_in_log(
        r"plugin-manager: started\([0-9].*\) /tmp/ltests-[a-z0-9_].*/test_poetry_install_1/lightning-1/reckless/testplugpyproj/testplugpyproj.py"
    )
    assert n.rpc.testmethod() == "I live."


@unittest.skipIf(VALGRIND, "virtual environment triggers memleak detection")
def test_local_dir_install(node_factory):
    """Test search and install from local directory source."""
    n = node_factory.get_node(options={})
    source_dir = str(
        Path(n.lightning_dir / ".." / "lightningd" / "testplugpass").resolve()
    )
    r = n.rpc.call("reckless", ["source", "-v", "add", source_dir])
    r = n.rpc.call("reckless", ["install", "-v", "testplugpass"])
    assert any("testplugpass enabled" in line for line in r["log"])
    plugin_path = Path(n.lightning_dir) / "reckless/testplugpass"
    print(plugin_path)
    assert os.path.exists(plugin_path)

    # Retry with a direct install passing the full path to the local source
    r = n.rpc.call("reckless", ["uninstall", "-v", "testplugpass"])
    assert not os.path.exists(plugin_path)
    r = n.rpc.call("reckless", ["source", "-v", "remove", source_dir])
    assert source_dir not in r["result"][0]["sources"]
    r = n.rpc.call("reckless", ["install", "-v", source_dir])
    print(r)
    assert any("testplugpass enabled" in line for line in r["log"])
    assert os.path.exists(plugin_path)


@unittest.skipIf(VALGRIND, "virtual environment triggers memleak detection")
def test_disable_enable(node_factory):
    """test search, git clone, and installation to folder."""
    n = node_factory.get_node(options={})
    # Test case-insensitive search as well
    r = n.rpc.call("reckless", ["install", "-v", "testPlugPass"])
    assert r["result"][0]["enabled"]
    assert r["result"][0]["plugin_name"] == "testplugpass"
    assert any("dependencies installed successfully" in line for line in r["log"])
    assert any("plugin installed:" in line for line in r["log"])
    assert any("testplugpass enabled" in line for line in r["log"])
    # r.check_stderr() TODO: check logs
    plugin_path = Path(n.lightning_dir) / "reckless/testplugpass"
    print(plugin_path)
    assert os.path.exists(plugin_path)
    r = n.rpc.call("reckless", ["disable", "-v", "testPlugPass"])
    assert r["result"][0]["plugin_name"] == "testplugpass"

    # Should find it with or without the file extension
    r = n.rpc.call("reckless", ["enable", "-v", "testplugpass.py"])
    assert r["result"][0]["plugin_name"] == "testplugpass"
    assert any("testplugpass enabled" in line for line in r["log"])
    test_plugin = {
        "name": str((plugin_path / "testplugpass.py").resolve()),
        "active": True,
        "dynamic": True,
    }
    time.sleep(1)
    print(n.rpc.plugin_list()["plugins"])
    assert test_plugin in n.rpc.plugin_list()["plugins"]


@unittest.skipIf(VALGRIND, "virtual environment triggers memleak detection")
def test_tag_install(node_factory):
    "install a plugin from a specific commit hash or tag"
    node = node_factory.get_node(options={})
    r = node.rpc.call("reckless", ["install", "-v", "testPlugPass"])
    assert r["result"][0]["enabled"]
    assert r["result"][0]["plugin_name"] == "testplugpass"
    metadata_file = node.lightning_dir / "reckless/testplugpass/.metadata.json"
    with open(metadata_file, "r") as md:
        metadata = json.load(md)
    assert "requested_commit" not in metadata["metadata"]
    # should install v2 (latest) without specifying
    version = node.rpc.gettestplugversion()
    assert version == "v2"
    r = node.rpc.call("reckless", ["uninstall", "-v", "testplugpass"])
    assert r["result"][0]["plugin_name"] == "testplugpass"
    r = node.rpc.call("reckless", ["install", "-v", "testplugpass@v1"])
    assert r["result"][0]["enabled"]
    assert r["result"][0]["plugin_name"] == "testplugpass"
    assert r["result"][0]["installed_commit"] == "v1"
    # v1 should now be checked out.
    version = node.rpc.gettestplugversion()
    assert version == "v1"
    installed_path = Path(node.lightning_dir) / "reckless/testplugpass"
    assert installed_path.is_dir()
    with open(metadata_file, "r") as md:
        metadata = json.load(md)
    assert metadata["metadata"]["requested_commit"] == "v1"
    assert metadata["metadata"]["installed_commit"] == "v1"


@unittest.skipIf(VALGRIND, "virtual environment triggers memleak detection")
def test_install_plugin_requiring_opts(node_factory):
    """A plugin that exits non-zero when run standalone (e.g. because a
    required option is not yet configured) should still install successfully."""
    node = node_factory.get_node(options={})
    r = node.rpc.call("reckless", ["install", "-v", "testplugreqopts"])
    assert not r["result"][0]["enabled"]
    assert r["result"][0]["plugin_name"] == "testplugreqopts"
    assert any("plugin installed:" in line for line in r["log"])
    assert any("testplugreqopts failed to start" in line for line in r["log"])
    assert all("testplugreqopts enabled" not in line for line in r["log"])
    assert any("may require options" in line for line in r["log"])
    plugin_path = Path(node.lightning_dir) / "reckless/testplugreqopts"
    assert plugin_path.exists()

    r = node.rpc.call(
        "reckless", ["enable", "-v", "testplugreqopts", "required-opt=foo"]
    )
    assert r["result"][0]["plugin_name"] == "testplugreqopts"
    assert any("testplugreqopts enabled" in line for line in r["log"])

    r = node.rpc.call("reckless", ["uninstall", "-v", "testplugreqopts"])
    assert r["result"][0]["plugin_name"] == "testplugreqopts"
    assert not plugin_path.exists()

    r = node.rpc.call(
        "reckless", ["install", "-v", "testplugreqopts", "required-opt=foo"]
    )
    assert r["result"][0]["enabled"]
    assert r["result"][0]["plugin_name"] == "testplugreqopts"
    assert any("plugin installed:" in line for line in r["log"])
    assert any("testplugreqopts enabled" in line for line in r["log"])


# Note: uv timeouts from the GH network seem to happen?
@pytest.mark.slow_test
@pytest.mark.flaky(max_runs=3, min_passes=1)
def test_reckless_uv_install(node_factory):
    node = node_factory.get_node(options={})
    r = node.rpc.call("reckless", ["install", "-v", "testpluguv"])
    assert r["result"][0]["enabled"]
    assert r["result"][0]["plugin_name"] == "testpluguv"
    installed_path = Path(node.lightning_dir) / "reckless/testpluguv"
    assert installed_path.is_dir()
    assert node.rpc.uvplugintest() == "I live."
    version = node.rpc.getuvpluginversion()
    assert version == "v1"

    assert any("using installer pythonuv" in line for line in r["log"])
    # r.check_stderr() TODO: check logs


@unittest.skipIf(VALGRIND, "virtual environment triggers memleak detection")
def test_reckless_manifest(node_factory):
    node, l2 = node_factory.line_graph(2, wait_for_announce=True)

    bolt12 = l2.rpc.call("offer", ["any"])["bolt12"]
    manifest = node.lightning_dir / ".." / "lightningd/testplugmani/manifest.json"
    with open(manifest, "r") as f:
        data = json.load(f)

    data["offer"] = bolt12

    with open(manifest, "w") as f:
        json.dump(data, f, indent=4)

    r = node.rpc.call("reckless", ["install", "-v", "testplugmani"])
    assert r["result"][0]["enabled"]
    assert r["result"][0]["plugin_name"] == "testplugmani"
    assert node.rpc.testmethod() == "I live."

    r = node.rpc.call("reckless", ["tip", "-v", "testplugmani", 1000])
    assert any(
        "Successfully sent 1000msat to testplugmani author!" in line
        for line in r["log"]
    )
