.TH "LIGHTNING-OPENCHANNEL_BUMP" "7" "" "" "lightning-openchannel_bump"
.SH NAME
lightning-openchannel_bump - Command to initiate a channel RBF
.SH SYNOPSIS

\fBopenchannel_bump\fR \fIchannel_id\fR \fIamount\fR \fIinitalpsbt\fR [\fIfunding_feerate\fR]

.SH DESCRIPTION

\fBopenchannel_bump\fR is a RPC command which initiates a channel
RBF (Replace-By-Fee) for the specified channel\. It uses the openchannel protocol
which allows for interactive transaction construction\.


\fIid\fR is the id of the channel to RBF\.


\fIamount\fR is the satoshi value that we will contribute to the channel\.
This value will be \fIadded\fR to the provided PSBT in the output which is
encumbered by the 2-of-2 script for this channel\.


\fIinitialpsbt\fR is the funded, incomplete PSBT that specifies the UTXOs and
change output for our channel contribution\. It can be updated,
see \fBopenchannel_update\fR; \fIinitialpsbt\fR must have at least one input\.
Must have the Non-Witness UTXO (PSBT_IN_NON_WITNESS_UTXO) set for
every input\. An error (code 309) will be returned if this requirement
is not met\.


\fIfunding_feerate\fR is an optional field\. Sets the feerate for the
funding transaction\. Defaults to 1/64th greater than the last
feerate used for this channel\.


Warning: bumping a leased channel will lose the lease\.

.SH RETURN VALUE

On success, an object is returned, containing:

.RS
.IP \[bu]
\fBchannel_id\fR (hex): the channel id of the channel (always 64 characters)
.IP \[bu]
\fBpsbt\fR (string): the (incomplete) PSBT of the RBF transaction
.IP \[bu]
\fBcommitments_secured\fR (boolean): whether the \fIpsbt\fR is complete (always \fIfalse\fR)
.IP \[bu]
\fBfunding_serial\fR (u64): the serial_id of the funding output in the \fIpsbt\fR

.RE

If the peer does not support \fBoption_dual_fund\fR, this command
will return an error\.


If the channel is not in a state that is eligible for RBF, this command
will return an error\.


On error the returned object will contain \fBcode\fR and \fBmessage\fR properties,
with \fBcode\fR being one of the following:

.RS
.IP \[bu]
-32602: If the given parameters are wrong\.
.IP \[bu]
-1: Catchall nonspecific error\.
.IP \[bu]
300: The amount exceeded the maximum configured funding amount\.
.IP \[bu]
301: The provided PSBT cannot afford the funding amount\.
.IP \[bu]
305: Peer is not connected\.
.IP \[bu]
309: PSBT missing required fields
.IP \[bu]
311: Unknown channel id\.
.IP \[bu]
312: Channel in an invalid state

.RE
.SH SEE ALSO

lightning-openchannel_\fBinit\fR(7), lightning-openchannel_\fBupdate\fR(7),
lightning-openchannel_\fBsigned\fR(7), lightning-openchannel_\fBabort\fR(7),
lightning-fundchannel_\fBstart\fR(7), lightning-fundchannel_\fBcomplete\fR(7),
\fBlightning-fundchannel\fR(7), \fBlightning-fundpsbt\fR(7), \fBlightning-utxopsbt\fR(7),
\fBlightning-multifundchannel\fR(7)

.SH AUTHOR

@niftynei \fI<niftynei@gmail.com\fR> is mainly responsible\.

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:eb53ca6e98a83063ac523123871b8bc32b0c9e60d0601d036883e7e7ee07177d
