.TH "LIGHTNING-DECODEPAY" "7" "" "" "lightning-decodepay"
.SH NAME
lightning-decodepay - Command for decoding a bolt11 string (low-level)
.SH SYNOPSIS

\fBdecodepay\fR \fIbolt11\fR [\fIdescription\fR]

.SH DESCRIPTION

The \fBdecodepay\fR RPC command checks and parses a \fIbolt11\fR string as
specified by the BOLT 11 specification\.

.SH RETURN VALUE

On success, an object is returned with the following fields, as
specified by BOLT11:

.RS
.IP \[bu]
\fIcurrency\fR: the BIP173 name for the currency\.
.IP \[bu]
\fItimestamp\fR: the UNIX-style timestamp of the invoice\.
.IP \[bu]
\fIexpiry\fR: the number of seconds this is valid after \fItimestamp\fR\.
.IP \[bu]
\fIpayee\fR: the public key of the recipient\.
.IP \[bu]
\fIpayment_hash\fR: the payment hash of the request\.
.IP \[bu]
\fIsignature\fR: the DER-encoded signature\.
.IP \[bu]
\fIdescription\fR: the description of the purpose of the purchase (see
below)

.RE

The following fields are optional:

.RS
.IP \[bu]
\fImsatoshi\fR: the number of millisatoshi requested (if any)\.
.IP \[bu]
\fIamount_msat\fR: the same as above, with \fImsat\fR appended (if any)\.
.IP \[bu]
\fIfallbacks\fR: array of fallback address object containing a \fIhex\fR
string, and both \fItype\fR and \fIaddr\fR if it is recognized as one of
\fIP2PKH\fR, \fIP2SH\fR, \fIP2WPKH\fR, or \fIP2WSH\fR\.
.IP \[bu]
\fIroutes\fR: an array of routes\. Each route is an arrays of objects,
each containing \fIpubkey\fR, \fIshort_channel_id\fR, \fIfee_base_msat\fR,
\fIfee_proportional_millionths\fR and \fIcltv_expiry_delta\fR\.
.IP \[bu]
\fIextra\fR: an array of objects representing unknown fields, each with
one-character \fItag\fR and a \fIdata\fR bech32 string\.

.RE

Technically, the \fIdescription\fR field is optional if a
\fIdescription_hash\fR field is given, but in this case \fBdecodepay\fR will
only succeed if the optional \fIdescription\fR field is passed and matches
the \fIdescription_hash\fR\. In practice, these are currently unused\.

.SH AUTHOR

Rusty Russell \fI<rusty@rustcorp.com.au\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-pay\fR(7), \fBlightning-getroute\fR(7), \fBlightning-sendpay\fR(7)\.


\fBBOLT
#11\fR (\fIhttps://github.com/lightningnetwork/lightning-rfc/blob/master/11-payment-encoding.md\fR)\.

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:d3944c14e16584577e0336dda8c2689881524717428eb921e23f8831144ec566
