.TH "LIGHTNING-LISTSENDPAYS" "7" "" "" "lightning-listsendpays"
.SH NAME
lightning-listsendpays - Low-level command for querying sendpay status
.SH SYNOPSIS

\fBlistsendpays\fR [\fIbolt11\fR] [\fIpayment_hash\fR]

.SH DESCRIPTION

The \fBlistsendpays\fR RPC command gets the status of all \fIsendpay\fR
commands (which is also used by the \fIpay\fR command), or with \fIbolt11\fR or
\fIpayment_hash\fR limits results to that specific payment\. You cannot
specify both\.


Note that in future there may be more than one concurrent \fIsendpay\fR
command per \fIpay\fR, so this command should be used with caution\.

.SH RETURN VALUE

On success, an array of objects is returned, ordered by increasing \fIid\fR\. Each object contains:


 \fIid\fR
unique internal value assigned at creation


 \fIpayment_hash\fR
the hash of the \fIpayment_preimage\fR which will prove payment\.


 \fIdestination\fR
the final destination of the payment\.


 \fIamount_msat\fR
the amount the destination received, in "NNNmsat" format\.


 \fIcreated_at\fR
the UNIX timestamp showing when this payment was initiated\.


 \fIstatus\fR
one of \fIcomplete\fR, \fIfailed\fR or \fIpending\fR\.


 \fIpayment_preimage\fR
(if \fIstatus\fR is \fIcomplete\fR) proves payment was received\.


 \fIlabel\fR
optional \fIlabel\fR, if provided to \fIsendpay\fR\.


 \fIbolt11\fR
the \fIbolt11\fR argument given to \fIpay\fR (may be missing for pre-0\.7
payments)\.


 \fIbolt12\fR
if \fBexperimental-offers\fR is enabled, and \fBpay\fR was a given a bolt12
invoice, this field will appear instead of \fIbolt11\fR\.

.SH AUTHOR

Christian Decker \fI<decker.christian@gmail.com\fR> is mainly
responsible\.

.SH SEE ALSO

\fBlightning-listpays\fR(7), \fBlightning-sendpay\fR(7), \fBlightning-listinvoice\fR(7)\.

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:c6b36205c8067723bb9edc20f3645754faa9c9d26568d6c899721b43a1e99812
