.TH "LIGHTNING-FUNDCHANNEL_START" "7" "" "" "lightning-fundchannel_start"
.SH NAME
lightning-fundchannel_start - Command for initiating channel establishment for a lightning channel
.SH SYNOPSIS

\fBfundchannel_start\fR \fIid\fR \fIamount\fR [\fIfeerate\fR \fIannounce\fR \fIclose_to\fR \fIpush_msat\fR]

.SH DESCRIPTION

\fBfundchannel_start\fR is a lower level RPC command\. It allows a user to
initiate channel establishment with a connected peer\.


\fIid\fR is the node id of the remote peer\.


\fIamount\fR is the satoshi value that the channel will be funded at\. This
value MUST be accurate, otherwise the negotiated commitment transactions
will not encompass the correct channel value\.


\fIfeerate\fR is an optional field\. Sets the feerate for subsequent
commitment transactions: see \fBfundchannel\fR\.


\fIannounce\fR whether or not to announce this channel\.


\fIclose_to\fR is a Bitcoin address to which the channel funds should be sent to
on close\. Only valid if both peers have negotiated \fBoption_upfront_shutdown_script\fR\.
Returns \fBclose_to\fR set to closing script iff is negotiated\.


\fIpush_msat\fR is the amount of millisatoshis to push to the channel peer at
open\. Note that this is a gift to the peer -- these satoshis are
added to the initial balance of the peer at channel start and are largely
unrecoverable once pushed\.


Note that the funding transaction MUST NOT be broadcast until after
channel establishment has been successfully completed by running
\fBfundchannel_complete\fR, as the commitment transactions for this channel
are not secured until the complete command succeeds\. Broadcasting
transaction before that can lead to unrecoverable loss of funds\.

.SH RETURN VALUE

On success, an object is returned, containing:

.RS
.IP \[bu]
\fBfunding_address\fR (string): The address to send funding to for the channel
.IP \[bu]
\fBscriptpubkey\fR (hex): The raw scriptPubkey for the address
.IP \[bu]
\fBclose_to\fR (hex, optional): The raw scriptPubkey which mutual close will go to; only present if \fIclose_to\fR parameter was specified and peer supports \fBoption_upfront_shutdown_script\fR

.RE

On error the returned object will contain \fBcode\fR and \fBmessage\fR properties,
with \fBcode\fR being one of the following:

.RS
.IP \[bu]
-32602: If the given parameters are wrong\.
.IP \[bu]
-1: Catchall nonspecific error\.
.IP \[bu]
300: The amount exceeded the maximum configured funding amount\.
.IP \[bu]
301: The provided \fBpush_msat\fR is greater than the provided \fBamount\fR\.
.IP \[bu]
304: Still syncing with bitcoin network
.IP \[bu]
305: Peer is not connected\.
.IP \[bu]
306: Unknown peer id\.

.RE
.SH AUTHOR

Lisa Neigut \fI<niftynei@gmail.com\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-connect\fR(7), \fBlightning-fundchannel\fR(7), \fBlightning-multifundchannel\fR(7),
lightning-fundchannel_\fBcomplete\fR(7), lightning-fundchannel_\fBcancel\fR(7)
lightning-openchannel_\fBinit\fR(7), lightning-openchannel_\fBupdate\fR(7),
lightning-openchannel_\fBsigned\fR(7), lightning-openchannel_\fBbump\fR(7),
lightning-openchannel_\fBabort\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:959e97d593fb77f9403e8c5024d5582a2ae81b5cffae1799a285e0a26281b770
