.TH "LIGHTNING-DELPAY" "7" "" "" "lightning-delpay"
.SH NAME
lightning-delpay - Command for removing a completed or failed payment
.SH SYNOPSIS

\fBdelpay\fR \fIpayment_hash\fR \fIstatus\fR

.SH DESCRIPTION

The \fBdelpay\fR RPC command deletes a payment with the given \fBpayment_hash\fR if its status is either \fBcomplete\fR or \fBfailed\fR\. Deleting a \fBpending\fR payment is an error\.

.RS
.IP \[bu]
\fIpayment_hash\fR: The unique identifier of a payment\.
.IP \[bu]
\fIstatus\fR: Expected status of the payment\. 
Only deletes if the payment status matches\.

.RE
.SH EXAMPLE JSON REQUEST
.nf
.RS
{
  "id": 82,
  "method": "delpay",
  "params": {
    "payment_hash": "4fa2f1b001067ec06d7f95b8695b8acd9ef04c1b4d1110e3b94e1fa0687bb1e0",
    "status": "complete"
  }
}
.RE

.fi
.SH RETURN VALUE

The returned format is the same as \fBlightning-listsendpays\fR(7)\.  If the
payment is a multi-part payment (MPP) the command return a list of
payments will be returned -- one payment object for each partid\.


On success, an object containing \fBpayments\fR is returned\.  It is an array of objects, where each object contains:

.RS
.IP \[bu]
\fBid\fR (u64): unique ID for this payment attempt
.IP \[bu]
\fBpayment_hash\fR (hex): the hash of the \fIpayment_preimage\fR which will prove payment (always 64 characters)
.IP \[bu]
\fBstatus\fR (string): status of the payment (one of "pending", "failed", "complete")
.IP \[bu]
\fBamount_sent_msat\fR (msat): the amount we actually sent, including fees
.IP \[bu]
\fBcreated_at\fR (u64): the UNIX timestamp showing when this payment was initiated
.IP \[bu]
\fBpartid\fR (u64, optional): unique ID within this (multi-part) payment
.IP \[bu]
\fBdestination\fR (pubkey, optional): the final destination of the payment if known
.IP \[bu]
\fBamount_msat\fR (msat, optional): the amount the destination received, if known
.IP \[bu]
\fBpayment_preimage\fR (hex, optional): proof of payment (always 64 characters)
.IP \[bu]
\fBlabel\fR (string, optional): the label, if given to sendpay
.IP \[bu]
\fBbolt11\fR (string, optional): the bolt11 string (if pay supplied one)
.IP \[bu]
\fBbolt12\fR (string, optional): the bolt12 string (if supplied for pay: \fBexperimental-offers\fR only)\.
.IP \[bu]
\fBerroronion\fR (hex, optional): the error onion returned on failure, if any\.

.RE

On failure, an error is returned\. If the lightning process fails before responding, the
caller should use \fBlightning-listsentpays\fR(7) or \fBlightning-listpays\fR(7) to query whether this payment was deleted or not\.


The following error codes may occur:

.RS
.IP \[bu]
-32602: Parameter missed or malformed;
.IP \[bu]
211: Payment status mismatch\. Check the correct status via \fBpaystatus\fR;
.IP \[bu]
208: Payment with payment_hash not found\.

.RE
.SH EXAMPLE JSON RESPONSE
.nf
.RS
{
   "payments": [
      {
         "id": 2,
         "payment_hash": "8dfd6538eeb33811c9114a75f792a143728d7f05643f38c3d574d3097e8910c0",
         "destination": "0219f8900ee78a89f050c24d8b69492954f9fdbabed753710845eb75d3a75a5880",
         "msatoshi": 1000,
         "amount_msat": "1000msat",
         "msatoshi_sent": 1000,
         "amount_sent_msat": "1000msat",
         "created_at": 1596224858,
         "status": "complete",
         "payment_preimage": "35bd4e2b481a1a84a22215b5372672cf81460a671816960ddb206464359e1822",
         "bolt11": "lntb10n1p0jga20pp53h7k2w8wkvuprjg3ff6l0y4pgdeg6lc9vsln3s74wnfsjl5fzrqqdqdw3jhxazldahx2xqyjw5qcqp2sp5wut5jnhr6n7jd5747ky2g5flmw7hgx9yjnqzu60ps2jf6f7tc0us9qy9qsqu2a0k37nckl62005p69xavlkydkvhnypk4dphffy4x09zltwh9437ad7xkl83tefdarzhu5t30ju5s56wlrg97qkx404pq3srfc425cq3ke9af"
      }
   ]
}
.RE

.fi
.SH AUTHOR

Vincenzo Palazzo \fI<vincenzo.palazzo@protonmail.com\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-listpays\fR(7), \fBlightning-listsendpays\fR(7), \fBlightning-paystatus\fR(7)\.

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:520f0b56c7288ed46509a0ab90be0959b3b1489b56b7e94f223de19cf7028758
