.TH "LIGHTNING-FUNDCHANNEL_CANCEL" "7" "" "" "lightning-fundchannel_cancel"
.SH NAME
lightning-fundchannel_cancel - Command for completing channel establishment
.SH SYNOPSIS

\fBfundchannel_cancel\fR \fIid\fR

.SH DESCRIPTION

\fBfundchannel_cancel\fR is a lower level RPC command\. It allows channel opener
to cancel a channel before funding broadcast with a connected peer\.


\fIid\fR is the node id of the remote peer with which to cancel\.


Note that the funding transaction MUST NOT be broadcast before
\fBfundchannel_cancel\fR\. Broadcasting transaction before \fBfundchannel_cancel\fR
WILL lead to unrecoverable loss of funds\.


If \fBfundchannel_cancel\fR is called after \fBfundchannel_complete\fR, the remote
peer may disconnect when command succeeds\. In this case, user need to connect
to remote peer again before opening channel\.

.SH RETURN VALUE

On success, an object is returned, containing:

.RS
.IP \[bu]
\fBcancelled\fR (string): A message indicating it was cancelled by RPC

.RE

On error the returned object will contain \fBcode\fR and \fBmessage\fR properties,
with \fBcode\fR being one of the following:

.RS
.IP \[bu]
-32602: If the given parameters are wrong\.
.IP \[bu]
306: Unknown peer id\.
.IP \[bu]
307: No channel currently being funded that can be cancelled\.
.IP \[bu]
308: It is unsafe to cancel the channel: the funding transaction
has been broadcast, or there are HTLCs already in the channel, or
the peer was the initiator and not us\.

.RE
.SH AUTHOR

Lisa Neigut \fI<niftynei@gmail.com\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-connect\fR(7), \fBlightning-fundchannel\fR(7), \fBlightning-multifundchannel\fR(7),
lightning-fundchannel_\fBstart\fR(7), lightning-fundchannel_\fBcomplete\fR(7)
lightning-openchannel_\fBinit\fR(7), lightning-openchannel_\fBupdate\fR(7),
lightning-openchannel_\fBsigned\fR(7), lightning-openchannel_\fBabort\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:d9006c6b2519f1ae2009a683e3e8131af6e182929d8f0025e451155e4e7d6fe6
