.TH "LIGHTNING-SIGNMESSAGE" "7" "" "" "lightning-signmessage"
.SH NAME
lightning-signmessage - Command to create a signature from this node
.SH SYNOPSIS

\fBsignmessage\fR \fImessage\fR

.SH DESCRIPTION

The \fBsignmessage\fR RPC command creates a digital signature of
\fImessage\fR using this node's secret key\.  A receiver who knows your
node's \fIid\fR and the \fImessage\fR can be sure that the resulting signature could
only be created by something with access to this node's secret key\.


\fImessage\fR must be less that 65536 characters\.

.SH RETURN VALUE

An object with attributes \fIsignature\fR, \fIrecid\fR and \fIzbase\fR is
returned\.  \fIzbase\fR is the result of \fIsignature\fR and \fIrecid\fR encoded in
a style compatible with \fBlnd\fR's \fBSignMessageRequest\fR (\fIhttps://api.lightning.community/#grpc-request-signmessagerequest\fR)\.

.SH AUTHOR

Rusty Russell \fI<rusty@rustcorp.com.au\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-checkmessage\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:e3565afa7011460ae5add0bd230b95699dadd1625ccb38bae02bc71136f468be
