.TH "LIGHTNING-ADDGOSSIP" "7" "" "" "lightning-addgossip"
.SH NAME
lightning-addgossip - Command for injecting a gossip message (low-level)
.SH SYNOPSIS

\fBaddgossip\fR \fImessage\fR

.SH DESCRIPTION

The \fBaddgossip\fR RPC command injects a hex-encoded gossip message into
the gossip daemon\.  It may return an error if it is malformed, or may
update its internal state using the gossip message\.


Note that currently some paths will still silently reject the gossip: it
is best effort\.


This is particularly used by plugins which may receive channel_update
messages within error replies\.

.SH RETURN VALUE

On success, an empty object is returned\.

.SH AUTHOR

Rusty Russell \fI<rusty@rustcorp.com.au\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-pay\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:dd8b1fd2ffcf7c57629a042f44f2fbc526d8892a2c933de6e82511721a8ffdea
