.TH "LIGHTNING-DELEXPIREDINVOICE" "7" "" "" "lightning-delexpiredinvoice"
.SH NAME
lightning-delexpiredinvoice - Command for removing expired invoices
.SH SYNOPSIS

\fBdelexpiredinvoice\fR [\fImaxexpirytime\fR]

.SH DESCRIPTION

The \fBdelexpiredinvoice\fR RPC command removes all invoices that have
expired on or before the given \fImaxexpirytime\fR\.


If \fImaxexpirytime\fR is not specified then all expired invoices are
deleted\.

.SH RETURN VALUE

On success, an empty object is returned\.

.SH AUTHOR

ZmnSCPxj \fI<ZmnSCPxj@protonmail.com\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-delinvoice\fR(7), \fBlightning-autocleaninvoice\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:a47d47609d9b39bbe6c0f0c61e28d255ceb496a49ad306db22ef23011c6f8cb8
