.TH "LIGHTNING-OPENCHANNEL_UPDATE" "7" "" "" "lightning-openchannel_update"
.SH NAME
lightning-openchannel_update - Command to update a collab channel open
.SH SYNOPSIS

\fBopenchannel_update\fR \fIchannel_id\fR \fIpsbt\fR

.SH DESCRIPTION

\fBopenchannel_update\fR is a low level RPC command which continues an open
channel, as specified by \fIchannel_id\fR\. An updated  \fIpsbt\fR is passed in; any
changes from the PSBT last returned (either from \fBopenchannel_init\fR or
a previous call to \fBopenchannel_update\fR) will be communicated to the peer\.


Must be called after \fBopenchannel_init\fR and before \fBopenchannel_signed\fR\.


Must be called until \fIcommitments_secured\fR is returned as true, at which point
\fBopenchannel_signed\fR should be called with a signed version of the PSBT
returned by the last call to \fBopenchannel_update\fR\.


\fIchannel_id\fR is the id of the channel\.


\fIpsbt\fR is the updated PSBT to be sent to the peer\. May be identical to
the PSBT last returned by either \fBopenchannel_init\fR or \fBopenchannel_update\fR\.

.SH RETURN VALUE

On success, returns the \fIchannel_id\fR for this channel; an updated, potentially
complete \fIpsbt\fR for this channel's funding transaction; and the flag
\fIcommitments_secured\fR, which indicates the completeness of the returned \fIpsbt\fR\.
If \fIcommitments_secured\fR is true, caller should proceed with signing the
returned PSBT and calling \fBopenchannel_signed\fR to complete the channel open\.


If \fIcommitments_secured\fR is true, will also return:

.RS
.IP \[bu]
The derived \fIchannel_id\fR\.
.IP \[bu]
A \fIclose_to\fR script, iff a \fBclose_to\fR address was provided to
\fBopenchannel_init\fR and the peer supports \fBoption_upfront_shutdownscript\fR\.
.IP \[bu]
The \fIfunding_outnum\fR, the index of the funding output for this channel
in the funding transaction\.

.RE
.RS
.IP \[bu]
-32602: If the given parameters are wrong\.
.IP \[bu]
-1: Catchall nonspecific error\.
.IP \[bu]
305: Peer is not connected\.
.IP \[bu]
309: PSBT missing required fields
.IP \[bu]
311: Unknown channel id\.

.RE
.SH SEE ALSO

lightning-openchannel_\fBupdate\fR(7), lightning-openchannel_\fBsigned\fR(7),
lightning-fundchannel_\fBstart\fR(7), lightning-fundchannel_\fBcomplete\fR(7),
\fBlightning-fundchannel\fR(7), \fBlightning-fundpsbt\fR(7), \fBlightning-utxopsbt\fR(7),
\fBlightning-multifundchannel\fR(7)

.SH AUTHOR

@niftynei \fI<niftynei@gmail.com\fR> is mainly responsible\.

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:de370bb6e61a0390a50a85e97f533238f379c908cddd822436d0ac4c72b43d6e
