.TH "LIGHTNING-LISTINVOICES" "7" "" "" "lightning-listinvoices"
.SH NAME
lightning-listinvoices - Command for querying invoice status
.SH SYNOPSIS

\fBlistinvoices\fR [\fIlabel\fR] [\fIinvstring\fR] [\fIpayment_hash\fR]

.SH DESCRIPTION

The \fBlistinvoices\fR RPC command gets the status of a specific invoice,
if it exists, or the status of all invoices if given no argument\.


A specific invoice can be queried by providing either the \fBlabel\fR
provided when creating the invoice, the \fBinvstring\fR string representing
the invoice, or the \fBpayment_hash\fR of the invoice\. Only one of the
query parameters can be used at once\.

.SH RETURN VALUE

On success, an array \fIinvoices\fR of objects is returned\. Each object contains
\fIlabel\fR, \fIdescription\fR, \fIpayment_hash\fR, \fIstatus\fR (one of \fIunpaid\fR, \fIpaid\fR or \fIexpired\fR),
\fIpayment_preimage\fR (for paid invoices), and \fIexpires_at\fR (a UNIX
timestamp)\.  If the \fImsatoshi\fR argument to \fBlightning-invoice\fR(7) was not "any",
there will be an \fImsatoshi\fR field as a number, and \fIamount_msat\fR as the same
number ending in \fImsat\fR\.  If the invoice was created with a bolt11 string,
there will be a \fIbolt11\fR field\.
If the invoice \fIstatus\fR is \fIpaid\fR, there will be a
\fIpay_index\fR field and an \fImsatoshi_received\fR field (which may be slightly
greater than \fImsatoshi\fR as some overpaying is permitted to allow clients to
obscure payment paths); there will also be an \fIamount_received_msat\fR field
with the same number as \fImsatoshi_received\fR but ending in \fImsat\fR\.

.SH AUTHOR

Rusty Russell \fI<rusty@rustcorp.com.au\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-waitinvoice\fR(7), \fBlightning-delinvoice\fR(7), \fBlightning-invoice\fR(7)\.

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:3d3cef4fa52635fa5c515959718e017173c3fffdc32ca7066fea3b82cf93758d
