.TH "LIGHTNING-WAITINVOICE" "7" "" "" "lightning-waitinvoice"
.SH NAME
lightning-waitinvoice - Command for waiting for specific payment
.SH SYNOPSIS

\fBwaitinvoice\fR \fIlabel\fR

.SH DESCRIPTION

The \fBwaitinvoice\fR RPC command waits until a specific invoice is paid,
then returns that single entry as per \fBlistinvoice\fR\.

.SH RETURN VALUE

On success, an invoice description will be returned as per
\fBlightning-listinvoice\fR(7)\. The \fIstatus\fR field will be \fIpaid\fR\.


If the invoice is deleted while unpaid, or the invoice does not exist,
this command will return with an error with code -1\.


If the invoice expires before being paid, or is already expired, this
command will return with an error with code -2, with the data being the
invoice data as per \fBlistinvoice\fR\.

.SH AUTHOR

Christian Decker \fI<decker.christian@gmail.com\fR> is mainly
responsible\.

.SH SEE ALSO

\fBlightning-waitanyinvoice\fR(7), \fBlightning-listinvoice\fR(7),
\fBlightning-delinvoice\fR(7), \fBlightning-invoice\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

.HL

Last updated 2019-04-07 14:23:17 CEST

