.TH "LIGHTNING-TXSEND" "7" "" "" "lightning-txsend"
.SH NAME
lightning-txsend - Command to sign and send transaction from txprepare
.SH SYNOPSIS

\fBtxsend\fR \fItxid\fR

.SH DESCRIPTION

The \fBtxsend\fR RPC command signs and broadcasts a transaction created by
\fBtxprepare\fR\.

.SH RETURN VALUE

On success, an object with attributes \fItx\fR and \fItxid\fR will be returned\.


\fItx\fR represents the fully signed raw bitcoin transaction, and \fItxid\fR is
the same as the \fItxid\fR argument\.


On failure, an error is reported (from bitcoind), and the inputs from
the transaction are unreserved\.


The following error codes may occur:

.RS
.IP \[bu]
-1: Catchall nonspecific error\.

.RE
.SH AUTHOR

Rusty Russell \fI<rusty@rustcorp.com.au\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-txprepare\fR(7), \fBlightning-txdiscard\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

