.TH "LIGHTNING-UNRESERVEINPUTS" "7" "" "" "lightning-unreserveinputs"
.SH NAME
lightning-unreserveinputs - Release reserved UTXOs
.SH SYNOPSIS

\fBunreserveinputs\fR \fIpsbt\fR

.SH DESCRIPTION

The \fBunreserveinputs\fR RPC command releases (or reduces reservation)
on UTXOs which were previously marked as reserved, generally by
\fBlightning-reserveinputs\fR(7)\.


The inputs to unreserve are the inputs specified in the passed-in \fIpsbt\fR\.

.SH RETURN VALUE

On success, an \fIreservations\fR array is returned, with an entry for each input
which was reserved:

.RS
.IP \[bu]
\fItxid\fR is the input transaction id\.
.IP \[bu]
\fIvout\fR is the input index\.
.IP \[bu]
\fIwas_reserved\fR indicates whether the input was already reserved (generally true)
.IP \[bu]
\fIreserved\fR indicates that the input is now reserved (may still be true, if it was previously reserved for a long time)\.
.IP \[bu]
\fIreserved_to_block\fR (if \fIreserved\fR is still true) indicates what blockheight the reservation will expire\.

.RE

On failure, an error is reported and no UTXOs are unreserved\.


The following error codes may occur:

.RS
.IP \[bu]
-32602: Invalid parameter, i\.e\. an unparseable PSBT\.

.RE
.SH AUTHOR

niftynei \fI<niftynei@gmail.com\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-unreserveinputs\fR(7), \fBlightning-signpsbt\fR(7), \fBlightning-sendpsbt\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

