.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-MAKESECRET" "7" "" "Core Lightning 0.12.1" ""
.SH
NAME
.LP
lightning-makesecret -- Command for deriving pseudorandom key from HSM
.SH
SYNOPSIS
.LP
\fBmakesecret\fR \fIhex\fR
.SH
DESCRIPTION
.LP
The \fBmakesecret\fR RPC command derives a secret key from the HSM_secret.
.PP
The \fIhex\fR can be any hex data.
.SH
RETURN VALUE
.LP
On success, an object is returned, containing:
.IP "\(bu" 2
\fBsecret\fR (secret): the pseudorandom key derived from HSM_secret (always 64 characters)
.LP
The following error codes may occur:
- -1: Catchall nonspecific error.
.SH
AUTHOR
.LP
Aditya <\fIaditya.sharma20111@gmail.com\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-getsharedsecret(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
\" SHA256STAMP:e5430e8948a10e24addc3a26717cfef0f56c84312d5a9156df3060d3770b66b3
