.TH "LIGHTNING-DISCONNECT" "7" "" "" "lightning-disconnect"
.SH NAME
lightning-disconnect - Command for disconnecting from another lightning node
.SH SYNOPSIS

\fBdisconnect\fR \fIid\fR [\fIforce\fR]

.SH DESCRIPTION

The disconnect RPC command closes an existing connection to a peer,
identified by \fIid\fR, in the Lightning Network, as long as it doesn’t have
an active channel\. If \fIforce\fR is set then it will disconnect even with
an active channel\.


The \fIid\fR can be discovered in the output of the listpeers command, which
returns a set of peers:

.nf
.RS
{
     "peers": [
          {
               "id": "0563aea81...",
               "connected": true,
               ...
          }
     ]
}


.RE

.fi

Passing the \fIid\fR attribute of a peer to \fIdisconnect\fR will terminate the
connection\.

.SH RETURN VALUE

On success, an empty object is returned\.


On error the returned object will contain \fBcode\fR and \fBmessage\fR properties,
with \fBcode\fR being one of the following:

.RS
.IP \[bu]
-32602: If the given parameters are wrong\.
.IP \[bu]
-1: Catchall nonspecific error\.

.RE
.SH AUTHOR

Michael Hawkins \fI<michael.hawkins@protonmail.com\fR>\.

.SH SEE ALSO

\fBlightning-connect\fR(1), \fBlightning-listpeers\fR(1)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:7efc0fbbb7397d3767ea170ba091b5bc00f4efaf8e1283c7b7ed1aaaccfd3c4d
