.TH "LIGHTNING-SIGNPSBT" "7" "" "" "lightning-signpsbt"
.SH NAME
lightning-signpsbt - Command to sign a wallet's inputs on a provided bitcoin transaction (PSBT)\.
.SH SYNOPSIS

\fBsignpsbt\fR \fIpsbt\fR [\fIsignonly\fR]

.SH DESCRIPTION

\fBsignpsbt\fR is a low-level RPC command which signs a PSBT as defined by
BIP-174\.

.RS
.IP \[bu]
\fIpsbt\fR: A base64-encoded string of the PSBT\.
.IP \[bu]
\fIsignonly\fR: An optional array of input numbers to sign\.

.RE

By default, all known inputs are signed, and others ignored: with
\fIsignonly\fR, only those inputs are signed, and an error is returned if
one of them cannot be signed\.


Note that the command will fail if there are no inputs to sign, or
if the inputs to be signed were not previously reserved\.

.SH EXAMPLE JSON REQUEST
.nf
.RS
{
  "id": 82,
  "method": "signpsbt",
  "params": {
    "psbt": "cHNidP8BAHEBAAAAAZ+dQXWMU0UUQW5guh1gAqRk6qV1EfswIxDz/l6pI4BYAAAAAAD/////AuQGAAAAAAAAFgAUNiXEouqXR2CoFjaP0V3ncVlEdue0RKASAAAAABYAFKswhKbTAJ6fHwhnBttaS62vUkitAAAAAAAAAAA="
  }
}
.RE

.fi
.SH RETURN VALUE

On success, a object will be returned with a string\.

.RS
.IP \[bu]
\fIpsbt\fR: A base64-PSBT with the specified inputs signed\.

.RE

On failure, one of the following error codes may be returned:

.RS
.IP \[bu]
-32602: Error in given parameters, or there aren't wallet's inputs to sign, or we couldn't sign all of \fIsignonly\fR, or inputs are not reserved\.

.RE
.SH EXAMPLE JSON RESPONSE
.nf
.RS
{
  "psbt": "cHNidP8BAHQBAAAAAcEKbzkcVvItfXURLb6PtIlar9N9jVKBZuxm34PsxGxgAAAAAAD/////AuQGAAAAAAAAFgAUNiXEouqXR2CoFjaP0V3ncVlEdueU1wUqAQAAABl2qRRxMMXp8bpyw7zzcTTnkjHukFng14isAAAAAAABAIUCAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wNSAQH/////AgDyBSoBAAAAF6kU8Lg4vWyj9numjGv33kmU8Xj7+XiHAAAAAAAAAAAmaiSqIant4vYcP3HR3v0/qZnfo2lTdVxpBol5mWK0i+vYNpdOjPkAAAAAAQEgAPIFKgEAAAAXqRTwuDi9bKP2e6aMa/feSZTxePv5eIcBBxcWABT3We/RPg4o3h4maqWGMKzDVE01JQEIawJHMEQCIDFf4Y8vEDgQEkYVPOMyZas7eDpL1In8OSqKhrYftufXAiAdGOETFcD4Ge/y5e9BAwJZYueRvfUnmCzFQhmA5F9oOwEhA5EQC8GjcXM6YayF40YJviaUnNI2O7BMaUHZOWS7qJAoAAAiAgMAI5tx4a99gMvc9XHlmZjIpfz56hXBUrCTKexXf1CyURDRNMcTAAAAgAAAAIAsAACAAA=="
}
.RE

.fi
.SH AUTHOR

Vincenzo Palazzo \fI<vincenzo.palazzo@protonmail.com\fR> wrote the initial version of this man page, but many others did the hard work of actually implementing this RPC command\.

.SH SEE ALSO

\fBlightning-fundpsbt\fR(7), \fBlightning-sendpsbt\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:f6463fb4a57eac3950a8d3876bd2c9bcd298f378f6fb98af0a1001b14161746e
