.TH "LIGHTNING-LISTNODES" "7" "" "" "lightning-listnodes"
.SH NAME
lightning-listnodes - Command to get the list of nodes in the known network\.
.SH SYNOPSIS

\fBlistnodes\fR [id]

.SH DESCRIPTION

The \fBlistnodes\fR command returns nodes the node has learned about via gossip messages, or a single one if the node \fIid\fR was specified\.

.SH EXAMPLE JSON REQUEST
.nf
.RS
{
  "id": 82,
  "method": "listnodes",
  "params": {
    "id": "02e29856dab8ddd9044c18486e4cab79ec717b490447af2d4831e290e48d57638a"
  }
}
.RE

.fi
.SH RETURN VALUE

On success, the command will return a list of nodes, each object represents a node, with the following details:

.RS
.IP \[bu]
\fInodeid\fR: Hex-encoded pubkey of the node\.

.RE

For nodes which have sent a node_announcement message, the following
are also returned:

.RS
.IP \[bu]
\fIalias\fR: The user-chosen node name as a string\.
.IP \[bu]
\fIcolor\fR: The user-chosen node color as a hexadecimal string\.
.IP \[bu]
\fIlast_timestamp\fR: The last-received node_announcement message as a UNIX timestamp integer\.
.IP \[bu]
\fIfeatures\fR: Hex-encoded features bitstring\.
.IP \[bu]
\fIaddresses\fR: An array of the node's public addresses\. Each address is represented by an object with the following properties:.RS
.IP \[bu]
\fItype\fR: Address type (\fB"ipv4"\fR, \fB"ipv6"\fR, \fB"torv2"\fR or \fB"torv3"\fR)\.
.IP \[bu]
\fIaddress\fR: IP or \fB.onion\fR hidden service address as a string\.
.IP \[bu]
\fIport\fR: Port number as an integer\.

.RE


.RE

On failure, one of the following error codes may be returned:

.RS
.IP \[bu]
-32602: Error in given parameters\.

.RE
.SH EXAMPLE JSON RESPONSE
.nf
.RS
{
   "nodes": [
      {
         "nodeid": "02e29856dab8ddd9044c14586e4cab79ec717b490447af2d4831e290e48d58638a",
         "alias": "some_alias",
         "color": "68f442",
         "last_timestamp": 1597213741,
         "features": "02a2a1",
         "addresses": [
            {
               "type": "ipv4",
               "address": "zzz.yy.xx.xx",
               "port": 9735
            }
         ]
      }
    ]
}
.RE

.fi
.SH AUTHOR

Vincenzo Palazzo \fI<vincenzo.palazzo@protonmail.com\fR> wrote the initial version of this man page, but many others did the hard work of actually implementing this rpc command\.

.SH SEE ALSO

FIXME:

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:b9e69c3b1db9430c998dff00a3221c0a7da0bd7af45dfcf4e26d12adf9656836
