'\" t
.\"     Title: lightning-cli
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 02/11/2018
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "LIGHTNING\-CLI" "1" "02/11/2018" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
lightning-cli \- Control lightning daemon
.SH "SYNOPSIS"
.sp
\fBlightning\-cli\fR [\fIOPTIONS\fR] \fIcommand\fR\&...
.SH "DESCRIPTION"
.sp
\fBlightning\-cli\fR sends commands to the lightning daemon\&.
.SH "OPTIONS"
.PP
\fB\-\-lightning\-dir\fR=\fIDIR\fR
.RS 4
Set the directory for the lightning daemon we\(cqre talking to; defaults to
\fI$HOME/\&.lightning\fR\&.
.RE
.PP
\fB\-\-rpc\-file\fR=\fIFILE\fR
.RS 4
Named pipe to use to talk to lightning daemon: default is
\fIlightning\-rpc\fR
in the lightning directory\&.
.RE
.PP
\fB\-\-keywords\fR/\fB\-k\fR
.RS 4
Use format
\fIkey\fR=\fIvalue\fR
for parameters in any order
.RE
.PP
\fB\-\-order\fR/\fB\-o\fR
.RS 4
Follow strictly the order of parameters for the command
.RE
.PP
\fB\-\-json\fR/\fB\-J\fR
.RS 4
Return result in JSON format (default unless
\fIhelp\fR
command)
.RE
.PP
\fB\-\-human\-readable\fR/\fB\-H\fR
.RS 4
Return result in human\-readable output (default for
\fIhelp\fR
command)
.RE
.PP
\fB\-\-help\fR/\fB\-h\fR
.RS 4
Print summary of options to standard output and exit\&.
.RE
.PP
\fB\-\-version\fR/\fB\-V\fR
.RS 4
Print version number to standard output and exit\&.
.RE
.SH "COMMANDS"
.sp
\fIlightning\-cli\fR simply uses the JSON RPC interface to talk to \fIlightningd\fR, and prints the results\&. Thus the commands available depend entirely on the lightning daemon itself\&.
.SH "ARGUMENTS"
.sp
Arguments may be provided positionally or using \fIkey\fR=\fIvalue\fR after the command name, based on either \fB\-o\fR or \fB\-k\fR option\&. Arguments may be integer numbers (composed entirely of digits), floating\-point numbers (has a radix point but otherwise composed of digits), \fItrue\fR, \fIfalse\fR, or \fInull\fR\&. Other arguments are treated as strings\&.
.sp
Some commands have optional arguments\&. You may use \fInull\fR to skip optional arguments to provide later arguments\&.
.SH "EXAMPLES"
.PP
\fBExample\ \&1.\ \&List commands\fR
.sp
lightning\-cli help
.SH "BUGS"
.sp
This manpage documents how it should work, not how it does work\&. The pretty printing of results isn\(cqt pretty\&.
.SH "AUTHOR"
.sp
Rusty Russell <rusty@rustcorp\&.com\&.au> is mainly to blame\&.
.SH "RESOURCES"
.sp
Main web site: https://github\&.com/ElementsProject/lightning
.SH "COPYING"
.sp
Note: the modules in the ccan/ directory have their own licenses, but the rest of the code is covered by the BSD\-style MIT license\&.
