.TH "LIGHTNING-LISTDATASTORE" "7" "" "" "lightning-listdatastore"
.SH NAME
lightning-listdatastore - Command for listing (plugin) data
.SH SYNOPSIS

\fBlistdatastore\fR [\fIkey\fR]

.SH DESCRIPTION

The \fBlistdatastore\fR RPC command allows plugins to fetch data which was
stored in the c-lightning database\.


All immediate children of the \fIkey\fR (or root children) are returned:
a \fIkey\fR with children won't have a \fIhex\fR or \fIgeneration\fR entry\.

.SH RETURN VALUE

On success, an object containing \fBdatastore\fR is returned\.  It is an array of objects, where each object contains:

.RS
.IP \[bu]
\fBkey\fR (array of strings):
.RS
.IP \[bu]
Part of the key added to the datastore

.RE

.IP \[bu]
\fBgeneration\fR (u64, optional): The number of times this has been updated
.IP \[bu]
\fBhex\fR (hex, optional): The hex data from the datastore
.IP \[bu]
\fBstring\fR (string, optional): The data as a string, if it's valid utf-8

.RE

The following error codes may occur:

.RS
.IP \[bu]
-32602: invalid parameters\.

.RE
.SH AUTHOR

Rusty Russell \fI<rusty@rustcorp.com.au\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-datastore\fR(7), \fBlightning-deldatastore\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:bf75b8d32d0c95b4b5d5b9e8c220afc7c26cf8eef318facc9fb2923fdc3ab93b
