.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-DISCONNECT" "7" "" "Core Lightning 0.12.1" ""
.SH
NAME
.LP
lightning-disconnect -- Command for disconnecting from another lightning node
.SH
SYNOPSIS
.LP
\fBdisconnect\fR \fIid\fR [\fIforce\fR]
.SH
DESCRIPTION
.LP
The disconnect RPC command closes an existing connection to a peer,
identified by \fIid\fR, in the Lightning Network, as long as it doesn't have
an active channel. If \fIforce\fR is set then it will disconnect even with
an active channel.
.PP
The \fIid\fR can be discovered in the output of the listpeers command, which
returns a set of peers:
.LP
.EX
{
     \(dqpeers\(dq: [
          {
               \(dqid\(dq: \(dq0563aea81...\(dq,
               \(dqconnected\(dq: true,
               ...
          }
     ]
}
.EE
.PP
Passing the \fIid\fR attribute of a peer to \fIdisconnect\fR will terminate the
connection.
.SH
RETURN VALUE
.LP
On success, an empty object is returned.
.PP
On error the returned object will contain \fCcode\fR and \fCmessage\fR properties,
with \fCcode\fR being one of the following:
.IP "\(bu" 2
-32602: If the given parameters are wrong.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
-1: Catchall nonspecific error.
.SH
AUTHOR
.LP
Michael Hawkins <\fImichael.hawkins@protonmail.com\fR>.
.SH
SEE ALSO
.LP
lightning-connect(1), lightning-listpeers(1)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
\" SHA256STAMP:d8bd29af48ec552d04c299cea5d3dacad93a02e2e50a3666dfb8865b05379576
