.TH "LIGHTNING-PLUGIN" "7" "" "" "lightning-plugin"
.SH NAME
lightning-plugin - Manage plugins with RPC
.SH SYNOPSIS

\fBplugin\fR command [parameter] [second_parameter]

.SH DESCRIPTION

The \fBplugin\fR RPC command allows to manage plugins without having to
restart lightningd\. It takes 1 to 3 parameters: a command
(start/stop/startdir/rescan/list) which describes the action to take and
optionally one or two parameters which describes the plugin on which the
action has to be taken\.


The \fIstart\fR command takes a path as the first parameter and will load
the plugin available from this path\.  Any additional parameters are
passed to the plugin\. It will wait for the plugin to complete the
handshake with \fBlightningd\fR for 20 seconds at the most\.


The \fIstop\fR command takes a plugin name as parameter\. It will kill and
unload the specified plugin\.


The \fIstartdir\fR command takes a directory path as first parameter and will
load all plugins this directory contains\. It will wait for each plugin to
complete the handshake with \fBlightningd\fR for 20 seconds at the most\.


The \fIrescan\fR command starts all not-already-loaded plugins from the
default plugins directory (by default \fI~/\.lightning/plugins\fR)\.


The \fIlist\fR command will return all the active plugins\.

.SH RETURN VALUE

On success, an object is returned, containing:

.RS
.IP \[bu]
\fBcommand\fR (string): the subcommand this is responding to (one of "start", "stop", "rescan", "startdir", "list")

.RE

If \fBcommand\fR is "start", "startdir", "rescan" or "list":

.RS
.IP \[bu]
\fBplugins\fR (array of objects):
.RS
.IP \[bu]
\fBname\fR (string): full pathname of the plugin
.IP \[bu]
\fBactive\fR (boolean): status; since plugins are configured asynchronously, a freshly started plugin may not appear immediately\.

.RE


.RE

If \fBcommand\fR is "stop":

.RS
.IP \[bu]
\fBresult\fR (string): A message saying it successfully stopped

.RE

On error, the reason why the action could not be taken upon the
plugin is returned\.

.SH AUTHOR

Antoine Poinsot \fI<darosior@protonmail.com\fR> is mainly responsible\.

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:281abf9aa97a3cb1204adc209541c3cfdcb1ca0126f62a126338dcd2fcd0bc8e
