.TH "LIGHTNING-WAITBLOCKHEIGHT" "7" "" "" "lightning-waitblockheight"
.SH NAME
lightning-waitblockheight - Command for waiting for blocks on the blockchain
.SH SYNOPSIS

\fBwaitblockheight\fR \fIblockheight\fR [\fItimeout\fR]

.SH DESCRIPTION

The \fBwaitblockheight\fR RPC command waits until the blockchain
has reached the specified \fIblockheight\fR\.
It will only wait up to \fItimeout\fR seconds (default 60)\.


If the \fIblockheight\fR is a present or past block height, then this
command returns immediately\.

.SH RETURN VALUE

On success, an object is returned, containing:

.RS
.IP \[bu]
\fBblockheight\fR (u32): The current block height (>= \fIblockheight\fR parameter)

.RE

If \fItimeout\fR seconds is reached without the specified blockheight
being reached, this command will fail with a code of \fB2000\fR\.

.SH AUTHOR

ZmnSCPxj \fI<ZmnSCPxj@protonmail.com\fR> is mainly responsible\.

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:38dc35b2a28f0ee342af0fdaba6b4f1f27fb1df973426804d30da0572eb3913d
