.TH "LIGHTNING-LISTFORWARDS" "7" "" "" "lightning-listforwards"
.SH NAME
lightning-listforwards - Command showing all htlcs and their information
.SH SYNOPSIS

\fBlistforwards\fR [\fIstatus\fR] [\fIin_channel\fR] [\fIout_channel\fR]

.SH DESCRIPTION

The \fBlistforwards\fR RPC command displays all htlcs that have been
attempted to be forwarded by the c-lightning node\.


If \fIstatus\fR is specified, then only the forwards with the given status are returned\.
\fIstatus\fR can be either \fIoffered\fR or \fIsettled\fR or \fIfailed\fR or \fIlocal_failed\fR


If \fIin_channel\fR or \fIout_channel\fR is specified, then only the matching forwards
on the given in/out channel are returned\.

.SH RETURN VALUE

On success, an object containing \fBforwards\fR is returned\.  It is an array of objects, where each object contains:

.RS
.IP \[bu]
\fBin_channel\fR (short_channel_id): the channel that received the HTLC
.IP \[bu]
\fBin_msat\fR (msat): the value of the incoming HTLC
.IP \[bu]
\fBstatus\fR (string): still ongoing, completed, failed locally, or failed after forwarding (one of "offered", "settled", "local_failed", "failed")
.IP \[bu]
\fBreceived_time\fR (number): the UNIX timestamp when this was received
.IP \[bu]
\fBout_channel\fR (short_channel_id, optional): the channel that the HTLC was forwarded to
.IP \[bu]
\fBpayment_hash\fR (hex, optional): payment hash sought by HTLC (always 64 characters)

.RE

If \fBout_channel\fR is present:

.RS
.IP \[bu]
\fBfee_msat\fR (msat): the amount this paid in fees
.IP \[bu]
\fBout_msat\fR (msat): the amount we sent out the \fIout_channel\fR

.RE

If \fBstatus\fR is "settled" or "failed":

.RS
.IP \[bu]
\fBresolved_time\fR (number): the UNIX timestamp when this was resolved

.RE

If \fBstatus\fR is "local_failed" or "failed":

.RS
.IP \[bu]
\fBfailcode\fR (u32, optional): the numeric onion code returned
.IP \[bu]
\fBfailreason\fR (string, optional): the name of the onion code returned

.RE
.SH AUTHOR

Rene Pickhardt \fI<r.pickhardt@gmail.com\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-getinfo\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:66506c6c5ebb9628f20bb6e20d696ac8e4b650d20e48ef8626e877f8447a1544
