.TH "LIGHTNING-SENDINVOICE" "7" "" "" "lightning-sendinvoice"
.SH NAME
lightning-sendinvoice - Command for send an invoice for an offer
.SH SYNOPSIS

\fIEXPERIMENTAL_FEATURES only\fR


\fBsendinvoice\fR \fIoffer\fR [\fIlabel\fR] [\fImsatoshi\fR] [\fItimeout\fR] [\fIquantity\fR]

.SH DESCRIPTION

The \fBsendinvoice\fR RPC command creates and sends an invoice to the
issuer of an \fIoffer\fR for it to pay: the offer must contain
\fIsend_invoice\fR; see \fBlightning-fetchinvoice\fR(7)\.


\fIoffer\fR is the bolt12 offer string beginning with "lno1"\.


\fIlabel\fR is the unique label to use for this invoice\.


\fImsatoshi\fR is optional: it is required if the \fIoffer\fR does not specify
an amount at all, or specifies it in a different currency\.  Otherwise
you may set it (e\.g\. to provide a tip), and if not it defaults to the
amount contained in the offer (multiplied by \fIquantity\fR if any)\.


\fItimeout\fR is how many seconds to wait for the offering node to pay the
invoice or return an error, default 90 seconds\.  This will also be the
timeout on the invoice that is sent\.


\fIquantity\fR is optional: it is required if the \fIoffer\fR specifies
\fIquantity_min\fR or \fIquantity_max\fR, otherwise it is not allowed\.

.SH RETURN VALUE

On success, an object as per \fBlightning-waitinvoice\fR(7)\.


The following error codes may occur:

.RS
.IP \[bu]
-1: Catchall nonspecific error\.
.IP \[bu]
1002: Offer has expired\.
.IP \[bu]
1003: Cannot find a route to the node making the offer\.
.IP \[bu]
1004: The node making the offer returned an error message\.
.IP \[bu]
1005: We timed out waiting for the invoice to be paid

.RE
.SH AUTHOR

Rusty Russell \fI<rusty@rustcorp.com.au\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-fetchinvoice\fR(7)\.

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:cfb235f88de77288c3a757f9d7252591cb61adb773d7a88062464011a6586753
