.TH "LIGHTNING-WAITINVOICE" "7" "" "" "lightning-waitinvoice"
.SH NAME
lightning-waitinvoice - Command for waiting for specific payment
.SH SYNOPSIS

\fBwaitinvoice\fR \fIlabel\fR

.SH DESCRIPTION

The \fBwaitinvoice\fR RPC command waits until a specific invoice is paid,
then returns that single entry as per \fBlistinvoice\fR\.

.SH RETURN VALUE

On success, an invoice description will be returned as per
\fBlightning-listinvoice\fR(7)\. The \fIstatus\fR field will be \fIpaid\fR or \fIexpired\fR\.


On error the returned object will contain \fBcode\fR and \fBmessage\fR properties,
with \fBcode\fR being one of the following:

.RS
.IP \[bu]
-32602: If the given parameters are wrong\.
.IP \[bu]
-1: If the invoice is deleted while unpaid, or the invoice does not exist\.
.IP \[bu]
903: If the invoice expires before being paid, or is already expired\.

.RE
.SH AUTHOR

Christian Decker \fI<decker.christian@gmail.com\fR> is mainly
responsible\.

.SH SEE ALSO

\fBlightning-waitanyinvoice\fR(7), \fBlightning-listinvoice\fR(7),
\fBlightning-delinvoice\fR(7), \fBlightning-invoice\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:afa7ad33136d9bd9a92b9e0c52387c3124f009ca11b045dbac4e840aaa610857
