.TH "LIGHTNING-LISTPAYS" "7" "" "" "lightning-listpays"
.SH NAME
lightning-listpays - Command for querying payment status
.SH SYNOPSIS

\fBlistpays\fR [bolt11] [payment_hash]

.SH DESCRIPTION

The \fBlistpay\fR RPC command gets the status of all \fIpay\fR commands, or a
single one if either \fIbolt11\fR or \fIpayment_hash\fR was specified\.

.SH RETURN VALUE

On success, an object containing \fBpays\fR is returned\.  It is an array of objects, where each object contains:

.RS
.IP \[bu]
\fBpayment_hash\fR (hex): the hash of the \fIpayment_preimage\fR which will prove payment (always 64 characters)
.IP \[bu]
\fBstatus\fR (string): status of the payment (one of "pending", "failed", "complete")
.IP \[bu]
\fBcreated_at\fR (u64): the UNIX timestamp showing when this payment was initiated
.IP \[bu]
\fBdestination\fR (pubkey, optional): the final destination of the payment if known
.IP \[bu]
\fBlabel\fR (string, optional): the label, if given to sendpay
.IP \[bu]
\fBbolt11\fR (string, optional): the bolt11 string (if pay supplied one)
.IP \[bu]
\fBbolt12\fR (string, optional): the bolt12 string (if supplied for pay: \fBexperimental-offers\fR only)\.

.RE

If \fBstatus\fR is "pending" or "complete":

.RS
.IP \[bu]
\fBamount_sent_msat\fR (msat): the amount we actually sent, including fees
.IP \[bu]
\fBamount_msat\fR (msat, optional): the amount the destination received, if known

.RE

If \fBstatus\fR is "complete":

.RS
.IP \[bu]
\fBpreimage\fR (hex): proof of payment (always 64 characters)
.IP \[bu]
\fBnumber_of_parts\fR (u64, optional): the number of parts for a successful payment (only if more than one)\.

.RE

If \fBstatus\fR is "failed":

.RS
.IP \[bu]
\fBerroronion\fR (hex, optional): the error onion returned on failure, if any\.

.RE

The returned array is ordered by increasing \fBcreated_at\fR fields\.

.SH AUTHOR

Rusty Russell \fI<rusty@rustcorp.com.au\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-pay\fR(7), \fBlightning-paystatus\fR(7), \fBlightning-listsendpays\fR(7)\.

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:4037a4dd9746b5dfc91ef2f5b4fa9000a334689157d9ac86dc4dba5c82628cfe
