.TH "LIGHTNING-WAITBLOCKHEIGHT" "7" "" "" "lightning-waitblockheight"
.SH NAME
lightning-waitblockheight - Command for waiting for blocks on the blockchain
.SH SYNOPSIS

\fBwaitblockheight\fR \fIblockheight\fR [\fItimeout\fR]

.SH DESCRIPTION

The \fBwaitblockheight\fR RPC command waits until the blockchain
has reached the specified \fIblockheight\fR\.
It will only wait up to \fItimeout\fR seconds (default 60)\.


If the \fIblockheight\fR is a present or past block height, then this
command returns immediately\.

.SH RETURN VALUE

Once the specified block height has been achieved by the blockchain,
an object with the single field \fIblockheight\fR is returned, which is
the block height at the time the command returns\.


If \fItimeout\fR seconds is reached without the specified blockheight
being reached, this command will fail with a code of \fB2000\fR\.

.SH AUTHOR

ZmnSCPxj \fI<ZmnSCPxj@protonmail.com\fR> is mainly responsible\.

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:ac3320b4b9e679d8c407e42c9663540e2fc2aca75143d192f58ce255ca9b3700
