.TH "LIGHTNING-AUTOCLEANINVOICE" "7" "" "" "lightning-autocleaninvoice"
.SH NAME
lightning-autocleaninvoice - Set up auto-delete of expired invoice
.SH SYNOPSIS

\fBautocleaninvoice\fR [\fIcycle_seconds\fR] [\fIexpired_by\fR]

.SH DESCRIPTION

The \fBautocleaninvoice\fR RPC command sets up automatic cleaning of
expired invoices\.


Autoclean will be done every \fIcycle_seconds\fR seconds\. Setting
\fIcycle_seconds\fR to 0 disables autoclean\. If not specified, this
defaults to 3600 (one hour)\.


Every autoclean cycle, expired invoices, which have already been expired
for at least \fIexpired_by\fR seconds, will be deleted\. If \fIexpired_by\fR is
not specified, this defaults to 86400 (one day)\.


On startup of the daemon, no autoclean is set up\.

.SH RETURN VALUE

On success, an object is returned, containing:

.RS
.IP \[bu]
\fBenabled\fR (boolean): whether invoice autocleaning is active

.RE

If \fBenabled\fR is \fItrue\fR:

.RS
.IP \[bu]
\fBexpired_by\fR (u64): how long an invoice must be expired (seconds) before we delete it
.IP \[bu]
\fBcycle_seconds\fR (u64): how long an invoice must be expired (seconds) before we delete it

.RE
.SH AUTHOR

ZmnSCPxj \fI<ZmnSCPxj@protonmail.com\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-delexpiredinvoice\fR(7), \fBlightning-delinvoice\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:dd3f512e81f45ab6084b608bc05fba5679b1d20d493aad98d422bdf593182604
