.TH "LIGHTNING-NEWADDR" "7" "" "" "lightning-newaddr"
.SH NAME
lightning-newaddr - Command for generating a new address to be used by c-lightning
.SH SYNOPSIS

\fBnewaddr\fR [ \fIaddresstype\fR ]

.SH DESCRIPTION

The \fBnewaddr\fR RPC command generates a new address which can
subsequently be used to fund channels managed by the c-lightning node\.


The funding transaction needs to be confirmed before funds can be used\.


\fIaddresstype\fR specifies the type of address wanted; i\.e\. \fIp2sh-segwit\fR
(e\.g\. 2MxaozoqWwiUcuD9KKgUSrLFDafLqimT9Ta on bitcoin testnet or
3MZxzq3jBSKNQ2e7dzneo9hy4FvNzmMmt3 on bitcoin mainnet) or \fIbech32 '
(e\.g\. tb1qu9j4lg5f9rgjyfhvfd905vw46eg39czmktxqgg on bitcoin testnet or
bc1qwqdg6squsna38e46795at95yu9atm8azzmyvckulcc7kytlcckxswvvzej on
bitcoin mainnet)\. The special value 'all\fR generates both address types
for the same underlying key\.


If not specified the address generated is bech32\.

.SH RETURN VALUE

On success, a \fIbech32\fR address and/or a \fIp2sh-segwit\fR address will be
returned\.

.SH ERRORS

If an unrecognized address type is requested an error message will be
returned\.

.SH AUTHOR

Felix \fI<fixone@gmail.com\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-listfunds\fR(7), \fBlightning-fundchannel\fR(7), \fBlightning-withdraw\fR(7), \fBlightning-listtransactions\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:00cbee36ae0e616fc3610191dfb1c14cb112971d9900fb8549ec66e4f700942f
