.TH "LIGHTNING-DELDATASTORE" "7" "" "" "lightning-deldatastore"
.SH NAME
lightning-deldatastore - Command for removing (plugin) data
.SH SYNOPSIS

\fBdeldatastore\fR \fIkey\fR

.SH DESCRIPTION

The \fBdeldatastore\fR RPC command allows plugins to delete data it has
stored in the c-lightning database\.


The command fails if the \fIkey\fR isn't present\.

.SH RETURN VALUE

On success, an object is returned, containing:

.RS
.IP \[bu]
\fBkey\fR (string): The key which has been removed from the datastore
.IP \[bu]
\fBhex\fR (hex): The hex data which has removed from the datastore

.RE

The main cause of failure is an non-existing entry\.


The following error codes may occur:

.RS
.IP \[bu]
-32602: invalid parameters, including non-existing key\.

.RE
.SH AUTHOR

Rusty Russell \fI<rusty@rustcorp.com.au\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-listdatastore\fR(7), \fBlightning-datastore\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:61af040ae88b08a8cc0e5f0d510a9613fbdc89e6e8d5b7dfebedcd134a91fb4b
