.TH "LIGHTNING-LISTNODES" "7" "" "" "lightning-listnodes"
.SH NAME
lightning-listnodes - Command to get the list of nodes in the own node network\.
.SH SYNOPSIS

\fBlistnodes\fR [id]

.SH DESCRIPTION

The \fBlistnodes\fR command returns nodes in the own node network, or a single one if the node \fIid\fR was specified\.

.SH EXAMPLE JSON REQUEST
.nf
.RS
{
  "id": 82,
  "method": "listnodes",
  "params": {
    "id": "02e29856dab8ddd9044c18486e4cab79ec717b490447af2d4831e290e48d57638a"
  }
}
.RE

.fi
.SH RETURN VALUE

On success, the command will return a list of nodes, each object represents a node, with the following details:

.RS
.IP \[bu]
\fInodeid\fR: A string that rappresents the node id\.
.IP \[bu]
\fIalias\fR: A string that rappresents alias of the node on the network\.
.IP \[bu]
\fIcolor\fR: A string that rappresents the personal color of the node\.
.IP \[bu]
\fIlast_timestamp\fR: An integer that rappresent the last timestamp\.
.IP \[bu]
\fIfeatures\fR: A string that rappresent the features value\.
.IP \[bu]
\fIaddresses\fR: An array that rappresent the addreses avaible\. Each address is rappresented with an object with the following properties:.RS
.IP \[bu]
\fItype\fR: A string that rappresent the address type (ipv4 or ipv6)\.
.IP \[bu]
\fIaddress\fR: A string that rappresent the address value\.
.IP \[bu]
\fIport\fR: An integer that rappresent the port number where the node are listening\.

.RE


.RE

On failure, one of the following error codes may be returned:

.RS
.IP \[bu]
-32602: Error in given parameters\.

.RE
.SH EXAMPLE JSON RESPONSE
.nf
.RS
{
   "nodes": [
      {
         "nodeid": "02e29856dab8ddd9044c14586e4cab79ec717b490447af2d4831e290e48d58638a",
         "alias": "some_alias",
         "color": "68f442",
         "last_timestamp": 1597213741,
         "features": "02a2a1",
         "addresses": [
            {
               "type": "ipv4",
               "address": "zzz.yy.xx.xx",
               "port": 9735
            }
         ]
      }
    ]
}
.RE

.fi
.SH AUTHOR

Vincenzo Palazzo \fI<vincenzo.palazzo@protonmail.com\fR> wrote the initial version of this man page, but many others did the hard work of actually implementing this rpc command\.

.SH SEE ALSO

FIXME: 

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

