.TH "LIGHTNING-GETLOG" "7" "" "" "lightning-getlog"
.SH NAME
lightning-getlog - Command to show logs\.
.SH SYNOPSIS

\fBgetlog\fR [\fIlevel\fR]

.SH DESCRIPTION

The \fBgetlog\fR the RPC command to show logs, with optional log \fIlevel\fR\.

.RS
.IP \[bu]
\fIlevel\fR: A string that represents the log level (\fIbroken\fR, \fIunusual\fR, \fIinfo\fR, \fIdebug\fR, or \fIio\fR)\.  The default is \fIinfo\fR\.

.RE
.SH EXAMPLE JSON REQUEST
.nf
.RS
{
  "id": 82,
  "method": "getlog",
  "params": {
    "level": "debug"
  }
}
.RE

.fi
.SH RETURN VALUE

On success, an object is returned, containing:

.RS
.IP \[bu]
\fBcreated_at\fR (string): UNIX timestamp with 9 decimal places, when logging was initialized
.IP \[bu]
\fBbytes_used\fR (u32): The number of bytes used by logging records
.IP \[bu]
\fBbytes_max\fR (u32): The bytes_used values at which records will be trimmed 
.IP \[bu]

\fBlog\fR (array of objects):

.RS
.IP \[bu]
\fBtype\fR (string) (one of "SKIPPED", "BROKEN", "UNUSUAL", "INFO", "DEBUG", "IO_IN", "IO_OUT")

.RE

If \fBtype\fR is "SKIPPED":

.RS
.IP \[bu]
\fBnum_skipped\fR (u32): number of unprinted log entries (deleted or below \fIlevel\fR parameter)

.RE

If \fBtype\fR is "BROKEN", "UNUSUAL", "INFO" or "DEBUG":

.RS
.IP \[bu]
\fBtime\fR (string): UNIX timestamp with 9 decimal places after \fBcreated_at\fR
.IP \[bu]
\fBsource\fR (string): The particular logbook this was found in
.IP \[bu]
\fBlog\fR (string): The actual log message
.IP \[bu]
\fBnode_id\fR (pubkey, optional): The peer this is associated with

.RE

If \fBtype\fR is "IO_IN" or "IO_OUT":

.RS
.IP \[bu]
\fBtime\fR (string): Seconds after \fBcreated_at\fR, with 9 decimal places
.IP \[bu]
\fBsource\fR (string): The particular logbook this was found in
.IP \[bu]
\fBlog\fR (string): The associated log message
.IP \[bu]
\fBdata\fR (hex): The IO which occurred
.IP \[bu]
\fBnode_id\fR (pubkey, optional): The peer this is associated with

.RE


.RE

On failure, one of the following error codes may be returned:

.RS
.IP \[bu]
-32602: Error in given parameters\.

.RE
.SH EXAMPLE JSON RESPONSE
.nf
.RS
{
   "created_at": "1598192543.820753463",
   "bytes_used": 89285843,
   "bytes_max": 104857600,
   "log": [
      {
         "type": "SKIPPED",
         "num_skipped": 45
      },
      {
         "type": "INFO",
         "time": "0.453627568",
         "source": "plugin-autopilot.py",
         "log": "RPC method 'autopilot-run-once' does not have a docstring."
      }
   ]
}
.RE

.fi
.SH AUTHOR

Vincenzo Palazzo \fI<vincenzo.palazzo@protonmail.com\fR> wrote the initial version of this man page, but many others did the hard work of actually implementing this rpc command\.

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:13e3ab43fb6811bff8bee102ba85e7d4cb8eb97d11bb0720ae5c0c576ba021ec
