.TH "LIGHTNING-FUNDCHANNEL_COMPLETE" "7" "" "" "lightning-fundchannel_complete"
.SH NAME
lightning-fundchannel_complete - Command for completing channel establishment
.SH SYNOPSIS

\fBfundchannel_complete\fR \fIid\fR \fIpsbt\fR

.SH DESCRIPTION

\fBfundchannel_complete\fR is a lower level RPC command\. It allows a user to
complete an initiated channel establishment with a connected peer\.


\fIid\fR is the node id of the remote peer\.


\fIpsbt\fR is the transaction to use for funding (does not need to be
signed but must be otherwise complete)\.


Note that the funding transaction MUST NOT be broadcast until after
channel establishment has been successfully completed, as the commitment
transactions for this channel are not secured until this command
successfully completes\. Broadcasting transaction before can lead to
unrecoverable loss of funds\.

.SH RETURN VALUE

On success, an object is returned, containing:

.RS
.IP \[bu]
\fBchannel_id\fR (hex): The channel_id of the resulting channel (always 64 characters)
.IP \[bu]
\fBcommitments_secured\fR (boolean): Indication that channel is safe to use (always \fItrue\fR)

.RE

On error the returned object will contain \fBcode\fR and \fBmessage\fR properties,
with \fBcode\fR being one of the following:

.RS
.IP \[bu]
-32602: If the given parameters are wrong\.
.IP \[bu]
-1: Catchall nonspecific error\.
.IP \[bu]
305: Peer is not connected\.
.IP \[bu]
306: Unknown peer id\.
.IP \[bu]
309: PSBT does not have a unique, correct output to fund the channel\.

.RE
.SH AUTHOR

Lisa Neigut \fI<niftynei@gmail.com\fR> is mainly responsible\.

.SH SEE ALSO

\fBlightning-connect\fR(7), \fBlightning-fundchannel\fR(7), \fBlightning-multifundchannel\fR(7),
lightning-fundchannel_\fBstart\fR(7), lightning-fundchannel_\fBcancel\fR(7),
lightning-openchannel_\fBinit\fR(7), lightning-openchannel_\fBupdate\fR(7),
lightning-openchannel_\fBsigned\fR(7), lightning-openchannel_\fBbump\fR(7),
lightning-openchannel_\fBabort\fR(7)

.SH RESOURCES

Main web site: \fIhttps://github.com/ElementsProject/lightning\fR

\" SHA256STAMP:72b7e8826beb42061bf53e59b72c35c4fba6cdb421e491ffe6bf07dc51412342
