#!/usr/bin/sh

THETEST=$1

PYTHONPATH=\
$PWD/contrib/pyln-client:\
$PWD/contrib/pyln-testing:\
$PWD/contrib/pyln-proto/: \
TEST_DEBUG=1 \
DEVELOPER=1 \
VALGRIND=0 \
SLOW_MACHINE=1 \
SUBDAEMON='hsmd:remote_hsmd' \
pytest \
$THETEST \
-v --timeout=550 --timeout_method=thread -x
