#!/usr/bin/sh

THETEST=$1

export PYTHONPATH=\
`pwd`/hsmd:\
`pwd`/contrib/pylightning:\
`pwd`/contrib/pyln-proto:\
`pwd`/contrib/pyln-testing:\
`pwd`/contrib/pyln-client:\
$PYTHONPATH

TEST_DEBUG=1 \
DEVELOPER=1 \
VALGRIND=0 \
SLOW_MACHINE=1 \
SUBDAEMON='hsmd:remote_hsmd' \
pytest \
$THETEST \
-v --timeout=550 --timeout_method=thread -x -s \
|& tee log
