#ifndef LIGHTNING_OPENINGD_DUAL_FUND_ROLES_H
#define LIGHTNING_OPENINGD_DUAL_FUND_ROLES_H

#define NUM_DF_RULES (OPENER + 1)
enum dual_fund_roles {
	ACCEPTER,
	OPENER,
};

#endif /* LIGHTNING_OPENINGD_DUAL_FUND_ROLES_H */
