#ifndef LIGHTNING_OPENINGD_DUAL_FUND_ROLES_H
#define LIGHTNING_OPENINGD_DUAL_FUND_ROLES_H

enum dual_fund_roles {
	ACCEPTER,
	OPENER,
	NUM_DF_RULES
};

#endif /* LIGHTNING_OPENINGD_DUAL_FUND_ROLES_H */
