name: CI Compilation testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { OS: alpine }
    steps:
      - uses: actions/checkout@v2
      - name: Integration testing
        run: |
          docker build -f contrib/docker/Dockerfile.${{matrix.OS}} -t clightning-${{matrix.OS}} .
