name: CI Compilation testing

on:
  workflow_run:
    workflows: [Pre-Builds Checks]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - { OS: alpine }
    on:
    steps:
      - uses: actions/checkout@v2
      - name: Integration testing
        run: |
          docker build -f contrib/docker/Dockerfile.${{matrix.OS}} -t clightning-${{matrix.OS}} .
